=== MangelMaxime/eleventy-layout-nacara/schemas/metadata-schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"required": [
		"url",
        "title",
        "description",
        "author"
	],
	"properties": {
        "$schema": {
            "type": "string"
        },
		"url": {
			"type": "string"
		},
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "editUrl": {
            "type": "string"
        },
        "baseUrl": {
            "type": "string"
        },
        "author": {
            "type": "object",
            "required": [
                "name",
                "twitter"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        }
	},
    "additionalProperties": false
}

=== MangelMaxime/eleventy-layout-nacara/tests/fixtures/breadcrumb-0/_data/nacaraMetadata.json
{
    "$schema": "./../../../schemas/metadata-schema.json",
    "url": "https://mangelmaxime.github.io",
    "editUrl": "https://github.com/MangelMaxime/Nacara/edit/master/docsrc",
    "baseUrl": "/Nacara/",
    "title": "Eleventy Nacara",
    "description": "",
    "author": {
        "name": "Maxime Mangel",
        "twitter": "MangelMaxime"
    }
}
